POST http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhVllTdVNIc2EyZnRRdW9Jb0YxV1FXazlrSHpqS05GUEhuTVJ2ZWZUeDhJIn0.eyJleHAiOjE3Mjg3NjI4NDYsImlhdCI6MTcyODc2MjU0NiwianRpIjoiMTkyZGY3NzktMTUxYy00ZTJmLTkwMjMtZDBiOGI2NTNhY2VhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlciIsImF1ZCI6ImVtYWlsbiIsInN1YiI6IjQ4OWZkOWFkLWM1NjctNDlhMS05YTkxLTAyZWFkYjUyOWZlZCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImVtYWlsbiIsInNlc3Npb25fc3RhdGUiOiI1MTYwNWE5Yy0xZTVmLTQxZDctOTI4Ny1hZmVjNzAyZTdiMWMiLCJzY29wZSI6IiIsInNpZCI6IjUxNjA1YTljLTFlNWYtNDFkNy05Mjg3LWFmZWM3MDJlN2IxYyJ9.KEaKrVaEt0TaMAZZSMccXX5i2K_f5tduQQG2Mryz-_rSKORKIxF9LPKAZVXRuIcZkPohhxcB3VopTNPpYkqG36qX2uuaci4dn9lofvhEjcgVHcj_13LWvISDvh0HwDSi1Kzl9YKOnSyWbAZ0i53GlaaW7A5kWmibGIoSUJHUu1eGHigj7o8_nYMEgcU125JczbYw-QlTPNut5ARQCF0BrpkGd_oOHW9qZ3KFjO8HFGyrvmstTwdyOX8xZqTw1fqApLP4n_Dqd92bQlxBGy2KWBQC1gzOl31Lr8HUMMLyyczrs3bVeJznm9biXssH70NSyhZUUN3Pp0BJiU_8zVe7WQ

{
    "name": "criarMultiploEmails23",
    "content": "createEmaailsteste",
    "emails": ["anamarina@testenovo.com.br","anamar@testemail.com.br","anamarina@testnew.com.br"]
}

###

GET  http://localhost:3000/campaigns/cs0q1nqiidqisk22cab0

####
PATCH http://localhost:3000/campaigns/cancel/cs0q1nqiidqisk22cab0


####
DELETE  http://localhost:3000/campaigns/delete/cs0q8rqiidqkn2f97b10

####
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=anamasantos&password=123456&grant_type=password

####
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded 

client_id=emailn&username=anamasantos&password=123456&grant_type=password