POST http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhVllTdVNIc2EyZnRRdW9Jb0YxV1FXazlrSHpqS05GUEhuTVJ2ZWZUeDhJIn0.eyJleHAiOjE3Mjg3NjIyNTgsImlhdCI6MTcyODc2MTk1OCwianRpIjoiZGI1YTc1NzItNDFkYS00NDNkLTlkODYtYWJmZDI0YTE3MTUwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlciIsImF1ZCI6ImVtYWlsbiIsInN1YiI6IjQ4OWZkOWFkLWM1NjctNDlhMS05YTkxLTAyZWFkYjUyOWZlZCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImVtYWlsbiIsInNlc3Npb25fc3RhdGUiOiI4Mzc4NjExOS1mNDViLTRmYmQtYTk1YS1kYzNkM2ZjODdmN2QiLCJzY29wZSI6IiIsInNpZCI6IjgzNzg2MTE5LWY0NWItNGZiZC1hOTVhLWRjM2QzZmM4N2Y3ZCJ9.hheSIsWMqbr4Hs8XR8VZ-WgymgQYzBt5pbfReNIF9rzO441OHJvbxipHlud5-9C_nXtfjsi846ryte_BIRdckpG1GZulNFN6O-IzdmQ0breH9D7t0KJKtbAiIFV2V1diwbWUCHzPpDUMdZUKbzsq6xTmWCSF5YLtf2vc-u-6BUkJMgbTn7-qoqlY4SUCPrthvZ-gEzTh2SxU8ua9HRQQzGkvtqvjgYRTZE71vP0IYF2w4g49U-TM3271UnDQ_cUYEJNiVVSvw9IFlJSIcBw78TDOxFHDZLROsNeYYHIuObTxgMunDPFh0kiOQMPMnU_TY23JbG17BtgXU5V87bMK_w

{
    "name": "criarMultiploEmails2",
    "content": "createEmaailsteste",
    "emails": ["anamarina@testenovo.com.br","anamar@testemail.com.br","anamarina@testnew.com.br"]
}

###

GET  http://localhost:3000/campaigns/cs0q1nqiidqisk22cab0

####
PATCH http://localhost:3000/campaigns/cancel/cs0q1nqiidqisk22cab0


####
DELETE  http://localhost:3000/campaigns/delete/cs0q8rqiidqkn2f97b10

####
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=anamasantos&password=123456&grant_type=password

####
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded 

client_id=emailn&username=anamasantos&password=123456&grant_type=password